AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for a DynamoDB Table

Resources:
  CreateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/app.handler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 10
      CodeUri: create-game/
      Environment:
        Variables:
          GAME_TABLE: !Ref GameTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameTable
      Events:
        CreateGameApi:
          Type: Api
          Properties:
            Path: /create-game
            Method: post

  DealHandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/app.handler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 10
      CodeUri: deal-hands/
      Environment:
        Variables:
          GAME_TABLE: !Ref GameTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameTable
      Events:
        DealHandsApi:
          Type: Api
          Properties:
            Path: /games/{gameId}/deal-hands  # Accepts gameId as a path parameter
            Method: post

  GetHandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/app.handler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 10
      CodeUri: get-hand/
      Environment:
        Variables:
          GAME_TABLE: !Ref GameTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameTable
      Events:
        GetHandApi:
          Type: Api
          Properties:
            Path: /games/{gameId}/players/{player}/hand  # Accepts gameId and player as path parameters
            Method: get

  GameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameTable
      BillingMode: PAY_PER_REQUEST # Adjust if you want provisioned capacity
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH # Partition key
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl # Optional for automatic record expiration
        Enabled: true
      Tags:
        - Key: Project
          Value: CardGameApp
